#!/bin/bash

# Desc: Automatically upgrade ubuntu from an EOL release
# Ref: https://help.ubuntu.com/community/EOLUpgrades

to_release="jammy"

# Set sources to "old-release"
sudo sed -i 's/^deb http:\/\/([^\.]+\.)+ubuntu\.com/deb http://old-releases.ubuntu.com/g' /etc/apt/sources.list

# Download latest upgrader
tmpd="$(mktemp -d)"
cd $tmpd
wget -O "$tmpd/${to_release}.tar.gz" "http://archive.ubuntu.com/ubuntu/dists/${to_release}-updates/main/dist-upgrader-all/current/${to_release}.tar.gz"
tar -xvf "$tmpd/${to_release}.tar.gz"
sudo bash "$tmpd/${to_release}"
